Added #9 largest-non-adjacent-sum
subsr97/daily-coding-problem pull request #1
Opened 2019-01-09 09:17 UTC by NandanSatheesh

largest-non-adjacent-sum was solved using Dynamic Programming approach.

2019-01-15 06:26 UTC, seeni-dev requested changes

2019-01-15 06:26 UTC, seeni-dev commented on challenges/largest-non-adjacent-sum.py
> +
What happens when len(array)==1 ?

2019-01-15 06:26 UTC, seeni-dev commented on challenges/largest-non-adjacent-sum.py
> +
and also it fails when len(array)==0.

2019-01-15 06:26 UTC, seeni-dev commented on challenges/largest-non-adjacent-sum.py
> +
space is O(n). It is not a constant space. If you look closely on the algorithm, you are using only three at any instance, DP_i, DP_i_1, DP_i_2. You can rewrite the alogithm to do that

2019-01-15 06:29 UTC, seeni-dev commented on challenges/largest-non-adjacent-sum.py
> +        print(DP)
as pointed out above rewrite this line to use constant space

2019-10-01 11:39 UTC, NandanSatheesh commented
Will make the necessary changes and raise a new PR again. Thanks for the feedback.

2019-10-01 11:39 UTC, closed without merging